name: Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - run: tests/external/bash-test/bash-test --sample amalgamate --tests tests/tests/

